apiVersion: v1
kind: Service
metadata:
  name: flask-app
  labels:
    app: flask-app
    component: greeting
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30010  # Fixed to a valid value
  selector:
    app: flask-app
    component: greeting
